[package]
name = "dlmm_tx"
version.workspace = true
edition.workspace = true

[dependencies]
dlmm_decode = { workspace = true }
solana-sdk = { workspace = true }
borsh = { workspace = true, features = ["derive"] }
eyre = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
