//! Property 3: every write function is safe to replay with identical input -- row counts
//! must not change on a second call. This is the property the whole ingestion design leans
//! on (a restarted worker or an at-least-once stream re-delivers the same event) and the
//! one most likely to break silently, since a missing `ON CONFLICT` clause still compiles
//! and still "works" the first time.
//!
//! Not every write function in `storage` gets a test here: `insert_signal` and
//! `open_paper_position` key on a fresh `Uuid` generated by the caller, not a natural key,
//! so replaying the *same* row is not a scenario production code ever produces -- doing so
//! deliberately hits the primary key and returns an error, which is correct, not a defect.
//! `rationale`/`position_marks`/`outcomes`, which key on a natural (parent_id, ordinal)
//! pair, are covered below instead.

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use std::str::FromStr;
use storage::types::{Timeframe, quality, venue};
use storage::write::{
    IndicatorRow, NewActiveBinSnapshot, NewBinState, NewDlmmPoolState, NewFeeParamUpdate,
    NewLiquidityEvent, NewOutcome, NewPaperPosition, NewPoolMetrics10mBucket, NewPoolMetricsBucket,
    NewPoolSnapshot, NewPositionMark, NewRationaleItem, NewRegimeStateRow, NewSignal, NewSwap,
    NewToken, NewVolatilityStateRow, insert_active_bin_snapshots, insert_bin_states,
    insert_fee_param_updates, insert_liquidity_events, insert_pool_state, insert_position_marks,
    insert_rationale, insert_signal_with_rationale, insert_swaps, mute_pool, open_paper_position,
    upsert_indicators, upsert_outcome, upsert_pool_metrics_5m, upsert_pool_metrics_10m,
    upsert_regime_state, upsert_token, upsert_volatility_state,
};

fn t() -> DateTime<Utc> {
    integration::fixture_time()
}

fn dec(s: &str) -> Decimal {
    Decimal::from_str(s).unwrap()
}

async fn row_count(pool: &sqlx::PgPool, table: &str, pool_address: &str) -> i64 {
    sqlx::query_scalar::<_, i64>(&format!(
        "SELECT count(*) FROM {table} WHERE pool_address = $1"
    ))
    .bind(pool_address)
    .fetch_one(pool)
    .await
    .unwrap_or_else(|e| panic!("counting rows in {table}: {e}"))
}

#[tokio::test]
async fn test_fee_param_update_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_fee_param_update";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let row = NewFeeParamUpdate {
        pool_address: pool_address.to_string(),
        ts: t(),
        slot: 10,
        signature: "sig_idempotent_fee_param".to_string(),
        field: "base_factor".to_string(),
        old_value: Some(10_000),
        new_value: Some(12_000),
    };

    insert_fee_param_updates(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();
    insert_fee_param_updates(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "fee_param_updates", pool_address).await, 1);
}

#[tokio::test]
async fn test_active_bin_snapshot_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_active_bin_snapshot";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let row = NewActiveBinSnapshot {
        pool_address: pool_address.to_string(),
        ts: t(),
        slot: 20,
        bin_id: 8_388_608,
        amount_x: dec("1000"),
        amount_y: dec("2000"),
        liquidity_supply: dec("3000"),
        quote_value_usd: Some(dec("42.5")),
    };

    insert_active_bin_snapshots(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();
    insert_active_bin_snapshots(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();

    assert_eq!(
        row_count(&pool, "active_bin_snapshots", pool_address).await,
        1
    );
}

#[tokio::test]
async fn test_bin_state_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_bin_state";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let row = NewBinState {
        pool_address: pool_address.to_string(),
        ts: t(),
        slot: 30,
        bin_id: 8_388_609,
        amount_x: dec("1000"),
        amount_y: dec("2000"),
        liquidity_supply: dec("3000"),
        price_q64: dec("18446744073709551616"),
        ui_price: 1.0,
        fee_x_per_token_stored: dec("1"),
        fee_y_per_token_stored: dec("2"),
    };

    insert_bin_states(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();
    insert_bin_states(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "bin_states", pool_address).await, 1);
}

#[tokio::test]
async fn test_pool_state_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_pool_state";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let ts = t();
    let snapshot = NewPoolSnapshot {
        pool_address: pool_address.to_string(),
        ts,
        slot: 40,
        price: 1.5,
        reserve_x_raw: Some(dec("1000")),
        reserve_y_raw: Some(dec("2000")),
        tvl_usd: Some(dec("50000")),
        active_tvl_usd: Some(dec("5000")),
        total_fee_bps: dec("30"),
    };
    let dlmm_state = NewDlmmPoolState {
        pool_address: pool_address.to_string(),
        ts,
        active_bin_id: 8_388_608,
        volatility_accumulator: 1_000,
        volatility_reference: 500,
        index_reference: 1,
        last_update_timestamp: 1_735_689_600,
        base_fee_bps: dec("20"),
        dynamic_fee_bps: dec("10"),
    };

    for _ in 0..2 {
        insert_pool_state(
            &pool,
            std::slice::from_ref(&snapshot),
            std::slice::from_ref(&dlmm_state),
        )
        .await
        .unwrap();
    }

    assert_eq!(row_count(&pool, "pool_snapshots", pool_address).await, 1);
    assert_eq!(row_count(&pool, "dlmm_pool_state", pool_address).await, 1);
}

#[tokio::test]
async fn test_pool_metrics_5m_upsert_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_pool_metrics_5m";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let bucket = NewPoolMetricsBucket {
        pool_address: pool_address.to_string(),
        bucket_start: t(),
        volume_usd: Some(dec("1000")),
        buy_volume_usd: Some(dec("600")),
        sell_volume_usd: Some(dec("400")),
        trade_fee_usd: Some(dec("3")),
        protocol_fee_usd: Some(dec("1")),
        swap_count: Some(5),
        unique_traders: Some(3),
        price_open: Some(1.0),
        price_high: Some(1.01),
        price_low: Some(0.99),
        price_close: Some(1.0),
        tvl_close: Some(dec("100000")),
        active_tvl_close: Some(dec("10000")),
        active_tvl_median: Some(dec("9500")),
        active_bin_open: Some(100),
        active_bin_close: Some(101),
        va_close: Some(12_000),
        total_fee_bps_close: Some(dec("30")),
        reserve_x_close: None,
        reserve_y_close: None,
        net_deposit_usd: Some(dec("500")),
        add_count: Some(1),
        remove_count: Some(0),
        lp_count_delta: None,
    };

    upsert_pool_metrics_5m(&pool, std::slice::from_ref(&bucket))
        .await
        .unwrap();
    upsert_pool_metrics_5m(&pool, std::slice::from_ref(&bucket))
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "pool_metrics_5m", pool_address).await, 1);
}

#[tokio::test]
async fn test_indicators_5m_upsert_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_indicators_5m";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let row = IndicatorRow {
        pool_address: pool_address.to_string(),
        venue: venue::DLMM,
        bucket_start: t(),
        quality: quality::MEASURED.to_string(),
        regime: Some("V1".to_string()),
        vol_change: Some(0.1),
        fee_change: None,
        tvl_change: None,
        price_change: None,
        active_tvl_change: None,
        holders_change: None,
        vol_tvl: Some(2.0),
        fee_tvl: None,
        fee_active_tvl: None,
        tau_a: Some(0.5),
        sigma_gk: Some(0.02),
        sigma_fast: Some(0.03),
        sigma_slow: Some(0.01),
        sigma_d: Some(0.02),
        sigma_jump: None,
        f_hat: Some(dec("30.5")),
        phi_org: Some(0.7),
        phi_mech: Some(0.6),
        phi_time: Some(0.8),
        phi_size: None,
        r_gross: Some(3.0),
        r_org: Some(2.5),
        y_fee: Some(0.3),
        top_score: None,
    };

    upsert_indicators(&pool, Timeframe::M5, std::slice::from_ref(&row))
        .await
        .unwrap();
    upsert_indicators(&pool, Timeframe::M5, std::slice::from_ref(&row))
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "indicators_5m", pool_address).await, 1);
}

#[tokio::test]
async fn test_rationale_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_rationale";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let signal_id = uuid::Uuid::new_v4();
    let signal = NewSignal {
        id: signal_id,
        ts: t(),
        pool_address: pool_address.to_string(),
        venue: venue::DLMM,
        timeframe: "5m".to_string(),
        kind: "POTENTIAL".to_string(),
        regime: Some("V1".to_string()),
        numbers: None,
        config_hash: "hash_idempotent_rationale".to_string(),
        expires_at: None,
    };
    let items = vec![NewRationaleItem {
        signal_id,
        seq: 0,
        venue: venue::DLMM,
        signal: "r_org".to_string(),
        observed: Some("2.5".to_string()),
        cmp: Some(">=".to_string()),
        threshold: Some("2.0".to_string()),
        passed: true,
        note: None,
    }];

    insert_signal_with_rationale(&pool, &signal, &items)
        .await
        .unwrap();

    // The signal itself has no natural key (a fresh row every real call, by design) --
    // only replaying the rationale rows for an already-existing signal is a realistic
    // scenario, e.g. a worker retrying the second half of a partially-failed write.
    insert_rationale(&pool, &items).await.unwrap();

    let count: i64 = sqlx::query_scalar("SELECT count(*) FROM rationale WHERE signal_id = $1")
        .bind(signal_id)
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(count, 1);
}

#[tokio::test]
async fn test_outcome_upsert_replay_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_outcome";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let position_id = uuid::Uuid::new_v4();
    open_paper_position(
        &pool,
        &NewPaperPosition {
            id: position_id,
            signal_id: None,
            pool_address: pool_address.to_string(),
            venue: venue::DLMM,
            opened_at: t(),
            regime: Some("V1".to_string()),
            entry_price: Some(1.5),
            entry_active_bin: Some(8_388_608),
            lower_bin: Some(8_388_600),
            upper_bin: Some(8_388_616),
            shape: Some("uniform".to_string()),
            size_usd: Some(dec("1000")),
            size_per_bin: Some(dec("62.5")),
            predicted: None,
        },
    )
    .await
    .unwrap();

    let outcome = NewOutcome {
        position_id,
        horizon: "24h".to_string(),
        venue: venue::DLMM,
        finalized_at: t() + chrono::Duration::hours(24),
        fees_real: Some(dec("12.5")),
        fees_predicted: Some(dec("10.0")),
        lvr_real: Some(dec("1.2")),
        r_real: Some(1.25),
        r_predicted: Some(1.0),
        time_in_range: Some(0.95),
        hit: Some(true),
    };

    upsert_outcome(&pool, &outcome).await.unwrap();
    upsert_outcome(&pool, &outcome).await.unwrap();

    let count: i64 =
        sqlx::query_scalar("SELECT count(*) FROM outcomes WHERE position_id = $1 AND horizon = $2")
            .bind(position_id)
            .bind(&outcome.horizon)
            .fetch_one(&pool)
            .await
            .unwrap();
    assert_eq!(count, 1);
}

#[tokio::test]
async fn test_upsert_pool_is_idempotent() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_upsert_pool";
    integration::reset_pool_fixture(&pool, pool_address).await;

    integration::ensure_pool(&pool, pool_address).await;
    integration::ensure_pool(&pool, pool_address).await;

    let count: i64 = sqlx::query_scalar("SELECT count(*) FROM pools WHERE pool_address = $1")
        .bind(pool_address)
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(count, 1);
}

#[tokio::test]
async fn test_upsert_token_is_idempotent() {
    let pool = integration::require_database!();
    let mint = "idempotent_token_mint_11111111111111111111111";
    sqlx::query("DELETE FROM tokens WHERE mint = $1")
        .bind(mint)
        .execute(&pool)
        .await
        .unwrap();

    let row = NewToken {
        mint: mint.to_string(),
        symbol: Some("TEST".to_string()),
        name: Some("Idempotency Test Token".to_string()),
        decimals: 9,
        mint_authority: None,
        freeze_authority: None,
        token_program: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA".to_string(),
        extensions: None,
        supply: Some(dec("1000000000")),
        holder_count: Some(100),
        top10_share: Some(0.1),
        top1_share: Some(0.05),
        is_verified: Some(true),
        rugcheck_score: None,
        rugcheck_flags: None,
        rugcheck_at: None,
        updated_at: t(),
    };

    upsert_token(&pool, &row).await.unwrap();
    upsert_token(&pool, &row).await.unwrap();

    let count: i64 = sqlx::query_scalar("SELECT count(*) FROM tokens WHERE mint = $1")
        .bind(mint)
        .fetch_one(&pool)
        .await
        .unwrap();
    assert_eq!(count, 1);
}

#[tokio::test]
async fn test_insert_swaps_is_idempotent_on_replay() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_swaps";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let row = NewSwap {
        pool_address: pool_address.to_string(),
        ts: t(),
        slot: 1,
        signature: "sig_idempotent_swap".to_string(),
        ix_index: 0,
        signer: "signer_idempotent_swap_1111111111111111111111".to_string(),
        swap_for_y: false,
        amount_in_raw: dec("1000000"),
        amount_out_raw: dec("2000000"),
        amount_in: dec("1"),
        amount_out: dec("2"),
        start_bin_id: 8_388_608,
        end_bin_id: 8_388_609,
        start_price: Some(dec("1.50")),
        end_price: Some(dec("1.51")),
        fee_raw: dec("1000"),
        protocol_fee_raw: dec("100"),
        host_fee_raw: None,
        fee_bps: dec("30"),
        volume_usd: Some(dec("1.5")),
        trade_fee_usd: Some(dec("0.009")),
        protocol_fee_usd: Some(dec("0.001")),
    };

    insert_swaps(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();
    insert_swaps(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "swaps", pool_address).await, 1);
}

#[tokio::test]
async fn test_insert_liquidity_events_is_idempotent_on_replay() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_liquidity_events";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let row = NewLiquidityEvent {
        pool_address: pool_address.to_string(),
        ts: t(),
        slot: 2,
        signature: "sig_idempotent_liquidity".to_string(),
        ix_index: 0,
        position_address: Some("position_idempotent_11111111111111111111111".to_string()),
        owner: "owner_idempotent_liquidity_1111111111111111111".to_string(),
        action: storage::types::liquidity_action::ADD,
        active_bin_id: 8_388_608,
        amount_x_raw: Some(dec("1000")),
        amount_y_raw: Some(dec("2000")),
        amount_usd: Some(dec("3")),
    };

    insert_liquidity_events(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();
    insert_liquidity_events(&pool, std::slice::from_ref(&row))
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "liquidity_events", pool_address).await, 1);
}

#[tokio::test]
async fn test_upsert_pool_metrics_10m_is_idempotent_on_replay() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_pool_metrics_10m";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let bucket = NewPoolMetrics10mBucket {
        bucket: NewPoolMetricsBucket {
            pool_address: pool_address.to_string(),
            bucket_start: t(),
            volume_usd: Some(dec("2000")),
            buy_volume_usd: Some(dec("1200")),
            sell_volume_usd: Some(dec("800")),
            trade_fee_usd: Some(dec("6")),
            protocol_fee_usd: Some(dec("2")),
            swap_count: Some(9),
            unique_traders: Some(4),
            price_open: Some(1.0),
            price_high: Some(1.02),
            price_low: Some(0.98),
            price_close: Some(1.01),
            tvl_close: Some(dec("100000")),
            active_tvl_close: Some(dec("10000")),
            active_tvl_median: Some(dec("9500")),
            active_bin_open: Some(100),
            active_bin_close: Some(102),
            va_close: Some(12_500),
            total_fee_bps_close: Some(dec("30")),
            reserve_x_close: None,
            reserve_y_close: None,
            net_deposit_usd: Some(dec("1000")),
            add_count: Some(2),
            remove_count: Some(0),
            lp_count_delta: None,
        },
        native_resolution: false,
    };

    upsert_pool_metrics_10m(&pool, std::slice::from_ref(&bucket))
        .await
        .unwrap();
    upsert_pool_metrics_10m(&pool, std::slice::from_ref(&bucket))
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "pool_metrics_10m", pool_address).await, 1);
}

#[tokio::test]
async fn test_regime_state_and_volatility_state_upserts_are_idempotent_on_replay() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_pipeline_state";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let now = t();
    let regime_row = NewRegimeStateRow {
        pool_address: pool_address.to_string(),
        venue: venue::DLMM,
        timeframe: "1h".to_string(),
        regime: Some("V1".to_string()),
        since: now,
        pending: None,
        pending_since: None,
        last_transition: Some(now),
        updated_at: now,
    };
    let volatility_row = NewVolatilityStateRow {
        pool_address: pool_address.to_string(),
        venue: venue::DLMM,
        timeframe: "1h".to_string(),
        sigma_fast_variance: 0.001,
        sigma_slow_variance: 0.0005,
        first_observed_at: now,
        updated_at: now,
    };

    upsert_regime_state(&pool, &regime_row).await.unwrap();
    upsert_regime_state(&pool, &regime_row).await.unwrap();
    upsert_volatility_state(&pool, &volatility_row)
        .await
        .unwrap();
    upsert_volatility_state(&pool, &volatility_row)
        .await
        .unwrap();

    assert_eq!(row_count(&pool, "regime_state", pool_address).await, 1);
    assert_eq!(row_count(&pool, "volatility_state", pool_address).await, 1);
}

#[tokio::test]
async fn test_mute_pool_is_idempotent_on_replay() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_mute_pool";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let until = t() + chrono::Duration::hours(6);
    mute_pool(&pool, pool_address, -1001, until).await.unwrap();
    mute_pool(&pool, pool_address, -1001, until).await.unwrap();

    assert_eq!(row_count(&pool, "muted_pools", pool_address).await, 1);
}

#[tokio::test]
async fn test_insert_position_marks_is_idempotent_on_replay() {
    let pool = integration::require_database!();
    let pool_address = "idempotent_position_marks";
    integration::ensure_pool(&pool, pool_address).await;
    integration::reset_pool_fixture(&pool, pool_address).await;

    let position_id = uuid::Uuid::new_v4();
    open_paper_position(
        &pool,
        &NewPaperPosition {
            id: position_id,
            signal_id: None,
            pool_address: pool_address.to_string(),
            venue: venue::DLMM,
            opened_at: t(),
            regime: Some("V1".to_string()),
            entry_price: Some(1.5),
            entry_active_bin: Some(8_388_608),
            lower_bin: Some(8_388_600),
            upper_bin: Some(8_388_616),
            shape: Some("uniform".to_string()),
            size_usd: Some(dec("1000")),
            size_per_bin: Some(dec("62.5")),
            predicted: None,
        },
    )
    .await
    .unwrap();

    let mark = NewPositionMark {
        position_id,
        ts: t(),
        price: Some(1.55),
        active_bin_id: Some(8_388_609),
        fees_accrued_usd: Some(dec("2.5")),
        il_usd: Some(dec("0.1")),
        value_usd: Some(dec("1002.5")),
        in_range: Some(true),
    };

    insert_position_marks(&pool, std::slice::from_ref(&mark))
        .await
        .unwrap();
    insert_position_marks(&pool, std::slice::from_ref(&mark))
        .await
        .unwrap();

    let count: i64 =
        sqlx::query_scalar("SELECT count(*) FROM position_marks WHERE position_id = $1")
            .bind(position_id)
            .fetch_one(&pool)
            .await
            .unwrap();
    assert_eq!(count, 1);
}
