[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true }
serde_yaml = { workspace = true }
